- [Dev]: fixed the module conflicts
Key:
default-version
Loading fftw/3.3.10--openmpi--4.1.6--nvhpc--23.11
  Loading requirement: openmpi/4.1.6--nvhpc--23.11

Loading openmpi/4.1.6--gcc--12.2.0
  ERROR: Conflicting openmpi is loaded

Loading hdf5/1.14.3--openmpi--4.1.6--gcc--12.2.0
  ERROR: Load of requirement openmpi/4.1.6--gcc--12.2.0 failed
Currently Loaded Modulefiles:
 1) profile/base   2) cintools/1.0   3) nvhpc/23.11   4) openmpi/4.1.6--nvhpc--23.11   5) fftw/3.3.10--openmpi--4.1.6--nvhpc--23.11

Key:
auto-loaded  default-version

Getting and compiling  : WarpX
Cloning into 'WarpX'...
remote: Enumerating objects: 79778, done.
remote: Counting objects: 100% (150/150), done.
remote: Compressing objects: 100% (104/104), done.
remote: Total 79778 (delta 92), reused 46 (delta 46), pack-reused 79628 (from 3)
Receiving objects: 100% (79778/79778), 82.13 MiB | 35.42 MiB/s, done.
Resolving deltas: 100% (61009/61009), done.
Updating files: 100% (1972/1972), done.
Progress : [-                                        #-] [= 2 <---> (secs) 100.00% =]
Loading openmpi/4.1.4--gcc--11.3.0-cuda-11.8
  ERROR: Module cannot be loaded due to a conflict.
    HINT: Might try "module unload openmpi" first.
Module list after WarpX:
Currently Loaded Modulefiles:
 1) profile/base   2) cintools/1.0   3) nvhpc/23.11   4) openmpi/4.1.6--nvhpc--23.11   5) fftw/3.3.10--openmpi--4.1.6--nvhpc--23.11

Key:
auto-loaded  default-version
done.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
/usr/bin/bash
Current path b4 scripts: ''/leonardo/home/userexternal/fbonnet0/SwanSea/SourceCodes/external_lib- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Connection to login.leonardo.cineca.it closed.