- [Dev]: fixed the module conflicts
Currently Loaded Modulefiles:
 1) profile/base   2) cintools/1.0

Key:
default-version
Loading fftw/3.3.10--openmpi--4.1.6--gcc--12.2.0
  Loading requirement: gcc/12.2.0 openmpi/4.1.6--gcc--12.2.0

Loading hdf5/1.14.3--openmpi--4.1.6--gcc--12.2.0
  Loading requirement: pkgconf/1.9.5--gcc--12.2.0-vplyjax zlib/1.3--gcc--12.2.0
Currently Loaded Modulefiles:
 1) profile/base   3) nvhpc/23.11   5) openmpi/4.1.6--gcc--12.2.0                 7) pkgconf/1.9.5--gcc--12.2.0-vplyjax   9) hdf5/1.14.3--openmpi--4.1.6--gcc--12.2.0
 2) cintools/1.0   4) gcc/12.2.0    6) fftw/3.3.10--openmpi--4.1.6--gcc--12.2.0   8) zlib/1.3--gcc--12.2.0

Key:
auto-loaded  default-version
! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! !
!                                                                       !
!     Code to load modules and prepare the base dependencies for grid   !
!     bash                                             !
!     [Author]: Frederic Bonnet October 2024                            !
!     [usage]: sh build_WarpX_leonardo.sh   {Input list}                !
!     [example]: sh build_WarpX_leonardo.sh {...}/SourceCodes/external_lib                   !
!                                                                       !
! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! !
Directory specified    : SwanSea/SourceCodes/external_lib will be the working target dir ...
! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! !
!                                                                       !
!     Code to load modules and prepare the base dependencies for grid   !
!     bash                                                    !
!     [Author]: Frederic Bonnet October 2024                            !
!     [usage]: sh common_main.sh   {Input list}                         !
!     [example]: sh common_main.sh /data/local                          !
!                                                                       !
! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! !
Directory specified    : SwanSea/SourceCodes/external_lib --->  will be the working target dir ...
Hostname               : login07.leonardo.local
Directory              : /leonardo/home/userexternal/fbonnet0/SwanSea/SourceCodes exist, nothing to do.
Directory              : /leonardo/home/userexternal/fbonnet0/SwanSea/SourceCodes/external_lib/grid_bench_202410 does not exist, We will create it ...
                       : done.
Directory              : /leonardo/home/userexternal/fbonnet0/SwanSea/SourceCodes/external_lib/prefix_grid_202410 does not exist, We will create it ...
                       : done.
Module load (script)   : String --> module_list : module load nvhpc/23.11 fftw/3.3.10--openmpi--4.1.6--gcc--12.2.0 hdf5; module list;
done.
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
Directory structure    : "bash"
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
hostname               : login07.leonardo.local
machine_name           : leonardo
build_dir              : build
sourcecode_dir         : /leonardo/home/userexternal/fbonnet0/SwanSea/SourceCodes
prefix Directory       : /leonardo/home/userexternal/fbonnet0/SwanSea/SourceCodes/external_lib/prefix_grid_202410
base Directory         : /leonardo/home/userexternal/fbonnet0/SwanSea/SourceCodes/external_lib/grid_bench_202410
grid directory         : /leonardo/home/userexternal/fbonnet0/SwanSea/SourceCodes/Grid-UCL-ARC/Grid
grid build directory   : /leonardo/home/userexternal/fbonnet0/SwanSea/SourceCodes/Grid-UCL-ARC/Grid/build
Hirep_LLR_SP directory : /leonardo/home/userexternal/fbonnet0/SwanSea/SourceCodes/Hirep_LLR_SP/Hirep_LLR_SP/
Hirep_LLR_SP_HMC dir   : /leonardo/home/userexternal/fbonnet0/SwanSea/SourceCodes/Hirep_LLR_SP/Hirep_LLR_SP//HMC
HiRep_Cuda directory   : /leonardo/home/userexternal/fbonnet0/SwanSea/SourceCodes/HiRep-Cuda/HiRep
Sombrero directory     : /leonardo/home/userexternal/fbonnet0/SwanSea/SourceCodes/Sombrero/SOMBRERO
BKeeper directory      : /leonardo/home/userexternal/fbonnet0/SwanSea/SourceCodes/BKeeper
Lattice runs directory : /leonardo/home/userexternal/fbonnet0/SwanSea/SourceCodes/LatticeRuns
<-- extrn_lib Fldr --->: bash
<-- Array length   --->: 15
<-- Max length dir --->: 95
<-- Source dir     --->: [001] --->: /leonardo/home/userexternal/fbonnet0/SwanSea/SourceCodes                                        ---> out_launch_Bench_Grid_HiRep_path_000.log
<-- Source dir     --->: [002] --->: /leonardo/home/userexternal/fbonnet0/SwanSea/SourceCodes/Sombrero/SOMBRERO                      ---> out_launch_Bench_Grid_HiRep_path_001.log
<-- Source dir     --->: [003] --->: /leonardo/home/userexternal/fbonnet0/SwanSea/SourceCodes/BKeeper                                ---> out_launch_Bench_Grid_HiRep_path_002.log
<-- Source dir     --->: [004] --->: /leonardo/home/userexternal/fbonnet0/SwanSea/SourceCodes/Bench_Grid_HiRep                       ---> out_launch_Bench_Grid_HiRep_path_003.log
<-- Source dir     --->: [005] --->: /leonardo/home/userexternal/fbonnet0/SwanSea/SourceCodes/Bench_Grid_HiRep/benchmarks            ---> out_launch_Bench_Grid_HiRep_path_004.log
<-- Source dir     --->: [006] --->: /leonardo/home/userexternal/fbonnet0/SwanSea/SourceCodes/Bench_Grid_HiRep/Scripts/Batch_Scripts ---> out_launch_Bench_Grid_HiRep_path_005.log
<-- Source dir     --->: [007] --->: /leonardo/home/userexternal/fbonnet0/SwanSea/SourceCodes/LatticeRuns                            ---> out_launch_Bench_Grid_HiRep_path_006.log
<-- Source dir     --->: [008] --->: /leonardo/home/userexternal/fbonnet0/SwanSea/SourceCodes/Hirep_LLR_SP/Hirep_LLR_SP/             ---> out_launch_Bench_Grid_HiRep_path_007.log
<-- Source dir     --->: [009] --->: /leonardo/home/userexternal/fbonnet0/SwanSea/SourceCodes/Hirep_LLR_SP/Hirep_LLR_SP//HMC         ---> out_launch_Bench_Grid_HiRep_path_008.log
<-- Source dir     --->: [010] --->: /leonardo/home/userexternal/fbonnet0/SwanSea/SourceCodes/HiRep-LLR-master/HiRep                 ---> out_launch_Bench_Grid_HiRep_path_009.log
<-- Source dir     --->: [011] --->: /leonardo/home/userexternal/fbonnet0/SwanSea/SourceCodes/HiRep-LLR-master/HiRep/LLR_HMC         ---> out_launch_Bench_Grid_HiRep_path_010.log
<-- Source dir     --->: [012] --->: /leonardo/home/userexternal/fbonnet0/SwanSea/SourceCodes/HiRep-Cuda/HiRep                       ---> out_launch_Bench_Grid_HiRep_path_011.log
<-- Source dir     --->: [013] --->: /leonardo/home/userexternal/fbonnet0/SwanSea/SourceCodes/Grid-UCL-ARC/Grid                      ---> out_launch_Bench_Grid_HiRep_path_012.log
<-- Source dir     --->: [014] --->: /leonardo/home/userexternal/fbonnet0/SwanSea/SourceCodes/external_lib/grid_bench_202410         ---> out_launch_Bench_Grid_HiRep_path_013.log
<-- Source dir     --->: [015] --->: /leonardo/home/userexternal/fbonnet0/SwanSea/SourceCodes/external_lib/prefix_grid_202410        ---> out_launch_Bench_Grid_HiRep_path_014.log
Waiting for procs ...
<-- Process done   --->: Continuing...

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Sun Jan 26 23:41:32 CET 2025
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-                  common_main.sh Done.                                 -
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Directory              : /leonardo/home/userexternal/fbonnet0/src does not exist, We will create it ...
                       : done.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Getting and compiling  : WarpX
Cloning into 'WarpX'...
remote: Enumerating objects: 79778, done.
remote: Counting objects: 100% (150/150), done.
remote: Compressing objects: 100% (104/104), done.
remote: Total 79778 (delta 92), reused 46 (delta 46), pack-reused 79628 (from 3)
Receiving objects: 100% (79778/79778), 82.13 MiB | 34.47 MiB/s, done.
Resolving deltas: 100% (61009/61009), done.
Updating files: 100% (1972/1972), done.
Progress : [-                                        #-] [= 2 <---> (secs) 100.00% =]
Loading gcc/11.3.0
  ERROR: Module cannot be loaded due to a conflict.
    HINT: Might try "module unload gcc" first.
Module list after WarpX:
Currently Loaded Modulefiles:
 1) profile/base   3) nvhpc/23.11   5) openmpi/4.1.6--gcc--12.2.0                 7) pkgconf/1.9.5--gcc--12.2.0-vplyjax   9) hdf5/1.14.3--openmpi--4.1.6--gcc--12.2.0
 2) cintools/1.0   4) gcc/12.2.0    6) fftw/3.3.10--openmpi--4.1.6--gcc--12.2.0   8) zlib/1.3--gcc--12.2.0

Key:
auto-loaded  default-version
done.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
/usr/bin/bash
Current path b4 scripts: ''/leonardo/home/userexternal/fbonnet0/SwanSea/SourceCodes/external_lib- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Connection to login.leonardo.cineca.it closed.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Sun Jan 26 10:41:40 PM GMT 2025
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-                  dispatcher_Grid_hiRep.sh Done.                       -
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Sun Jan 26 10:41:40 PM GMT 2025
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-                  deploy_to_clusters.sh Done.                          -
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[Linux][22:41:40] frederic@DESKTOP-GPI5ERK:~/SwanSea/SourceCodes/Bench_Grid_HiRep (master)() =>$